import packageJson from "../../../../package.json";

export function ReportFooter({ generatedAt }: { generatedAt: string }) {
  return (
    <footer className="border-t border-border pt-4 text-center text-xs text-muted-foreground">
      Generated by Vault Analyser v{packageJson.version} ·{" "}
      {new Date(generatedAt).toLocaleString()}
    </footer>
  );
}
