"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { StepActions, StepHeader } from "@/components/workflow/step-navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useProjectStore, type Measurement as ProjectMeasurement } from "@/lib/store";
import {
  calculateApexSpan,
  calculateCustomRibGroups,
  calculateImpostLine,
  detectRibGroups,
  getBossStoneMarkers,
  getImportedTraces,
  getIntradosLines,
  getMeasurementConfig,
  type ApexSpanResult,
  type BossStoneMarker,
  type ImpostLineResult,
  type MeasurementConfig,
  type RibGroup,
  type RibPairing,
  type SemicircularGroupInput,
} from "@/lib/api";
import {
  coerceTraceSourceSelection,
  normalizeImportedCurves,
  resolveAvailableTraceSource,
  toWorkflowTraceLineFromImportedCurve,
  toWorkflowTraceLineFromIntrados,
  type WorkflowTraceLine,
} from "@/lib/traces";
import { formatNumber } from "@/lib/utils";
import {
  Box,
  CheckCircle,
  ChevronLeft,
  Circle,
  Download,
  Grid3X3,
  Home,
  Loader2,
  RefreshCw,
  Table,
  type LucideIcon,
} from "lucide-react";

type DisplayGroup = RibGroup & {
  source: "custom" | "auto" | "single";
};

interface RibSummaryRow {
  id: string;
  name: string;
  source: DisplayGroup["source"];
  ribCount: number;
  arcRadius: number | null;
  arcRadiusText: string;
  length: number | null;
  lengthText: string;
  impostDistance: number | null;
  impostDistanceText: string;
  span: number | null;
  spanText: string;
  apexHeight: number | null;
  apexHeightText: string;
  fitError: number | null;
  fitErrorText: string;
}

interface BossSummaryRow {
  id: string;
  name: string;
  groupId: string;
  x: number;
  y: number;
  z: number;
  heightFromImpost: number | null;
  heightFromImpostText: string;
  connectedRibCount: number;
  apexPairCount: number;
  source: "pairings" | "boss-apex" | "n/a";
}

const EMPTY_MEASUREMENT_CONFIG: MeasurementConfig = {
  ribNameById: {},
  customGroups: [],
  disabledAutoGroupIds: [],
  groupNameById: {},
  bossStoneNameById: {},
  ribPairings: [],
  semicircularIds: [],
};

const AUTO_GROUP_NAME_SENTINEL = "__AUTO_COMPOSED_GROUP_NAME__";
const LEGACY_AUTO_GROUP_NAME_PATTERN = /^Group \d+$/i;
const RIB_NAME_DELIMITER = /\s*-\s*/;
const STRAIGHT_LINE_RATIO = 10;

function formatMetric(value: number | undefined | null, digits = 2): string {
  if (value == null || Number.isNaN(value)) return "n/a";
  return value.toFixed(digits);
}

function formatMeters(value: number, digits = 2): string {
  return `${value.toFixed(digits)}m`;
}

function hasFiniteNumber(value: number | undefined | null): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function hasDisplayableRadius(radius: number | undefined | null, ribLength?: number | null): radius is number {
  if (radius == null || radius <= 0) return false;
  const threshold = ribLength != null && ribLength > 0 ? STRAIGHT_LINE_RATIO * ribLength : 500;
  return radius <= threshold;
}

function toCsvCell(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((left, right) => left - right);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 !== 0 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

function isAutoGeneratedGroupName(name?: string | null): boolean {
  const trimmed = name?.trim();
  return !trimmed || trimmed === AUTO_GROUP_NAME_SENTINEL || LEGACY_AUTO_GROUP_NAME_PATTERN.test(trimmed);
}

function parseRibPathName(name: string): [string, string] | null {
  const parts = name
    .split(RIB_NAME_DELIMITER)
    .map((part) => part.trim())
    .filter(Boolean);

  if (parts.length !== 2 || parts[0] === parts[1]) {
    return null;
  }

  return [parts[0], parts[1]];
}

function composeConnectedRibPathName(paths: Array<{ name: string; order: number; nodes: [string, string] }>): string {
  const adjacency = new Map<string, string[]>();

  paths.forEach((path) => {
    const [start, end] = path.nodes;
    adjacency.set(start, [...(adjacency.get(start) ?? []), end]);
    adjacency.set(end, [...(adjacency.get(end) ?? []), start]);
  });

  if (Array.from(adjacency.values()).some((neighbors) => neighbors.length > 2)) {
    return paths.map((path) => path.name).join(" + ");
  }

  const endpoints = Array.from(adjacency.entries())
    .filter(([, neighbors]) => neighbors.length === 1)
    .map(([node]) => node);

  if (adjacency.size === 1) {
    return Array.from(adjacency.keys())[0];
  }

  if (endpoints.length !== 2) {
    return paths.map((path) => path.name).join(" + ");
  }

  const firstPath = paths[0].nodes;
  const start = firstPath.find((node) => endpoints.includes(node)) ?? endpoints[0];
  const orderedNodes = [start];
  let previous: string | null = null;
  let current = start;

  while (true) {
    const nextNodes = (adjacency.get(current) ?? []).filter((node) => node !== previous);
    if (nextNodes.length === 0) {
      break;
    }
    if (nextNodes.length > 1) {
      return paths.map((path) => path.name).join(" + ");
    }
    const next = nextNodes[0];
    orderedNodes.push(next);
    previous = current;
    current = next;
    if (orderedNodes.length > adjacency.size) {
      return paths.map((path) => path.name).join(" + ");
    }
  }

  if (orderedNodes.length !== adjacency.size) {
    return paths.map((path) => path.name).join(" + ");
  }

  return orderedNodes.join("-");
}

function composeRibGroupName(names: string[]): string | undefined {
  if (names.length === 0) {
    return undefined;
  }

  const parsedPaths = names.map((name, order) => {
    const nodes = parseRibPathName(name);
    return nodes ? { name, order, nodes } : null;
  });

  if (parsedPaths.some((path) => path == null)) {
    return names.join(" + ");
  }

  const remaining = [...(parsedPaths as Array<{ name: string; order: number; nodes: [string, string] }>)];
  const components: Array<{ order: number; label: string }> = [];

  while (remaining.length > 0) {
    const current = [remaining.shift()!];
    const visited = new Set(current.flatMap((path) => path.nodes));

    let changed = true;
    while (changed) {
      changed = false;
      for (let index = remaining.length - 1; index >= 0; index -= 1) {
        const path = remaining[index];
        if (path.nodes.some((node) => visited.has(node))) {
          current.push(path);
          path.nodes.forEach((node) => visited.add(node));
          remaining.splice(index, 1);
          changed = true;
        }
      }
    }

    current.sort((left, right) => left.order - right.order);
    components.push({
      order: current[0].order,
      label: composeConnectedRibPathName(current),
    });
  }

  components.sort((left, right) => left.order - right.order);
  return components.map((component) => component.label).join(" + ");
}

function downloadCsv(fileName: string, content: string): void {
  const blob = new Blob([content], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

function MetricCard(props: {
  title: string;
  value: string;
  description: string;
  icon: LucideIcon;
}) {
  const { title, value, description, icon: Icon } = props;
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-start justify-between gap-3">
          <div>
            <p className="text-xs uppercase tracking-wide text-muted-foreground">{title}</p>
            <p className="mt-1 text-2xl font-semibold">{value}</p>
            <p className="mt-1 text-xs text-muted-foreground">{description}</p>
          </div>
          <Icon className="h-5 w-5 text-muted-foreground" />
        </div>
      </CardContent>
    </Card>
  );
}

export default function Step8AnalysisPage() {
  const router = useRouter();
  const { currentProject, completeStep } = useProjectStore();

  const requestedTraceSource = coerceTraceSourceSelection(currentProject?.stepData?.[6]?.traceSource);
  const step5ImpostLineZ = currentProject?.stepData?.[5]?.impostLineZ as number | undefined;

  const [reloadNonce, setReloadNonce] = useState(0);
  const [isSummaryLoading, setIsSummaryLoading] = useState(false);
  const [summaryError, setSummaryError] = useState<string | null>(null);
  const [isDetectingGroups, setIsDetectingGroups] = useState(false);
  const [isLoadingImpost, setIsLoadingImpost] = useState(false);
  const [isLoadingApexSpan, setIsLoadingApexSpan] = useState(false);
  const [exportingRibs, setExportingRibs] = useState(false);
  const [exportingBosses, setExportingBosses] = useState(false);

  const [measurementConfig, setMeasurementConfig] = useState<MeasurementConfig>(EMPTY_MEASUREMENT_CONFIG);
  const [autoTraceLines, setAutoTraceLines] = useState<WorkflowTraceLine[]>([]);
  const [manualTraceLines, setManualTraceLines] = useState<WorkflowTraceLine[]>([]);
  const [bossStoneMarkers, setBossStoneMarkers] = useState<BossStoneMarker[]>([]);
  const [ribGroups, setRibGroups] = useState<RibGroup[] | null>(null);
  const [customGroupMetrics, setCustomGroupMetrics] = useState<Record<string, RibGroup["combinedMeasurements"]>>({});
  const [impostLineData, setImpostLineData] = useState<ImpostLineResult | null>(null);
  const [apexSpanResult, setApexSpanResult] = useState<ApexSpanResult | null>(null);

  const hasAutoTraceLines = autoTraceLines.length > 0;
  const hasManualTraceLines = manualTraceLines.length > 0;

  const activeTraceSource = useMemo(
    () => resolveAvailableTraceSource(requestedTraceSource, hasAutoTraceLines, hasManualTraceLines),
    [requestedTraceSource, hasAutoTraceLines, hasManualTraceLines],
  );

  const intradosLines = useMemo(() => {
    if (activeTraceSource === "manual") {
      return manualTraceLines;
    }
    if (activeTraceSource === "both") {
      return [...autoTraceLines, ...manualTraceLines];
    }
    return autoTraceLines;
  }, [activeTraceSource, autoTraceLines, manualTraceLines]);

  const activeTraceSummary = useMemo(() => {
    if (activeTraceSource === "manual") {
      return `${manualTraceLines.length} imported manual ${manualTraceLines.length === 1 ? "trace" : "traces"}`;
    }
    if (activeTraceSource === "both") {
      const total = autoTraceLines.length + manualTraceLines.length;
      return `${total} traces (${autoTraceLines.length} auto, ${manualTraceLines.length} manual)`;
    }
    return `${autoTraceLines.length} auto-detected ${autoTraceLines.length === 1 ? "trace" : "traces"}`;
  }, [activeTraceSource, autoTraceLines.length, manualTraceLines.length]);

  const ribLabelById = useMemo(() => {
    const next = new Map<string, string>();
    intradosLines.forEach((line) => {
      next.set(line.id, line.label);
    });
    return next;
  }, [intradosLines]);

  const getRibDisplayName = useCallback(
    (ribId: string) => {
      return measurementConfig.ribNameById[ribId] ?? ribLabelById.get(ribId) ?? ribId;
    },
    [measurementConfig.ribNameById, ribLabelById],
  );

  const composeGroupName = useCallback(
    (ribIds: string[]) => {
      const names = ribIds
        .map(getRibDisplayName)
        .map((name) => name.trim())
        .filter(Boolean);
      return composeRibGroupName(names);
    },
    [getRibDisplayName],
  );

  const resolveGroupName = useCallback(
    (name: string | undefined, ribIds: string[]) => {
      if (isAutoGeneratedGroupName(name)) {
        return composeGroupName(ribIds);
      }
      return name?.trim();
    },
    [composeGroupName],
  );

  useEffect(() => {
    const loadSummaryData = async () => {
      if (!currentProject?.id) {
        setAutoTraceLines([]);
        setManualTraceLines([]);
        setBossStoneMarkers([]);
        setMeasurementConfig(EMPTY_MEASUREMENT_CONFIG);
        setSummaryError(null);
        return;
      }

      setIsSummaryLoading(true);
      setSummaryError(null);

      try {
        const [linesResult, manualResult, bossResult, configResult] = await Promise.allSettled([
          getIntradosLines(currentProject.id),
          getImportedTraces(currentProject.id),
          getBossStoneMarkers(currentProject.id),
          getMeasurementConfig(currentProject.id),
        ]);

        if (linesResult.status === "fulfilled" && linesResult.value.success && linesResult.value.data?.lines) {
          setAutoTraceLines(linesResult.value.data.lines.map(toWorkflowTraceLineFromIntrados));
        } else {
          setAutoTraceLines([]);
        }

        if (manualResult.status === "fulfilled" && manualResult.value.success) {
          const curves = normalizeImportedCurves(manualResult.value.data?.curves, manualResult.value.data?.source ?? null);
          setManualTraceLines(curves.map((curve, index) => toWorkflowTraceLineFromImportedCurve(curve, index)));
        } else {
          setManualTraceLines([]);
        }

        if (bossResult.status === "fulfilled" && bossResult.value.success && bossResult.value.data?.markers) {
          setBossStoneMarkers(bossResult.value.data.markers);
        } else {
          setBossStoneMarkers([]);
        }

        if (configResult.status === "fulfilled" && configResult.value.success && configResult.value.data) {
          setMeasurementConfig(configResult.value.data);
        } else {
          setMeasurementConfig(EMPTY_MEASUREMENT_CONFIG);
        }

        const linesFailed = linesResult.status === "rejected" || (linesResult.status === "fulfilled" && !linesResult.value.success);
        const configFailed = configResult.status === "rejected" || (configResult.status === "fulfilled" && !configResult.value.success);
        if (linesFailed || configFailed) {
          setSummaryError("Some Step 7 summary inputs could not be loaded. Available data is shown below.");
        }
      } catch (err) {
        console.error("Error loading Step 8 summary data:", err);
        setAutoTraceLines([]);
        setManualTraceLines([]);
        setBossStoneMarkers([]);
        setMeasurementConfig(EMPTY_MEASUREMENT_CONFIG);
        setSummaryError("Unable to load Step 7 summary data.");
      } finally {
        setIsSummaryLoading(false);
      }
    };

    void loadSummaryData();
  }, [currentProject?.id, reloadNonce]);

  useEffect(() => {
    const loadRibGroups = async () => {
      if (intradosLines.length === 0) {
        setRibGroups(null);
        return;
      }

      setIsDetectingGroups(true);
      try {
        const response = await detectRibGroups({
          ribs: intradosLines.map((line) => ({ id: line.id, points: line.points3d })),
          maxGap: 0.35,
          angleThresholdDeg: 12,
          radiusTolerance: 0.1,
          bossGapFactor: 0.4,
          planeNormalThresholdDeg: 15,
          bosses: bossStoneMarkers.filter((marker) => marker.groupId !== "roi_corner").map((marker) => ({ x: marker.x, y: marker.y, z: marker.z })),
        });

        if (response.success && response.data) {
          setRibGroups(response.data);
        } else {
          setRibGroups(null);
        }
      } catch (err) {
        console.error("Error detecting rib groups for Step 8 summary:", err);
        setRibGroups(null);
      } finally {
        setIsDetectingGroups(false);
      }
    };

    void loadRibGroups();
  }, [intradosLines, bossStoneMarkers]);

  useEffect(() => {
    const loadCustomGroupMetrics = async () => {
      if (measurementConfig.customGroups.length === 0 || intradosLines.length === 0) {
        setCustomGroupMetrics({});
        return;
      }

      try {
        const response = await calculateCustomRibGroups({
          ribs: intradosLines.map((line) => ({ id: line.id, points: line.points3d })),
          groups: measurementConfig.customGroups.map((group) => ({
            groupId: group.id,
            groupName: resolveGroupName(group.name, group.ribIds),
            ribIds: group.ribIds,
          })),
        });

        if (response.success && response.data) {
          const byId: Record<string, RibGroup["combinedMeasurements"]> = {};
          response.data.forEach((group) => {
            byId[group.groupId] = group.combinedMeasurements;
          });
          setCustomGroupMetrics(byId);
        } else {
          setCustomGroupMetrics({});
        }
      } catch (err) {
        console.error("Error computing custom group metrics for Step 8 summary:", err);
        setCustomGroupMetrics({});
      }
    };

    void loadCustomGroupMetrics();
  }, [measurementConfig.customGroups, intradosLines, resolveGroupName]);

  useEffect(() => {
    const loadImpost = async () => {
      if (intradosLines.length === 0) {
        setImpostLineData(null);
        return;
      }

      setIsLoadingImpost(true);
      setImpostLineData(null);
      try {
        const response = await calculateImpostLine({
          ribs: intradosLines.map((line) => ({ id: line.id, points: line.points3d })),
          impostHeight: step5ImpostLineZ,
        });

        if (response.success && response.data) {
          setImpostLineData(response.data);
        }
      } catch (err) {
        console.error("Error calculating impost line for Step 8 summary:", err);
      } finally {
        setIsLoadingImpost(false);
      }
    };

    void loadImpost();
  }, [intradosLines, step5ImpostLineZ]);

  const measurementById = useMemo(() => {
    const map = new Map<string, ProjectMeasurement>();
    if (!currentProject) {
      return map;
    }

    currentProject.measurements.forEach((measurement) => {
      map.set(measurement.id, measurement);
    });
    return map;
  }, [currentProject]);

  const displayGroups = useMemo((): DisplayGroup[] => {
    const result: DisplayGroup[] = [];
    const assigned = new Set<string>();

    const fallbackCombined = (ribIds: string[]): RibGroup["combinedMeasurements"] => {
      const members = ribIds.map((ribId) => measurementById.get(ribId)).filter(Boolean) as Array<{
        arcRadius: number;
        ribLength: number;
      }>;
      const count = Math.max(members.length, 1);
      const avgRadius = members.reduce((acc, member) => acc + member.arcRadius, 0) / count;
      const totalLength = members.reduce((acc, member) => acc + member.ribLength, 0);
      return {
        arc_radius: avgRadius,
        rib_length: totalLength,
        apex_point: { x: 0, y: 0, z: 0 },
        arc_center: { x: 0, y: 0, z: 0 },
        arc_center_z: 0,
        fit_error: 0,
      };
    };

    for (const group of measurementConfig.customGroups) {
      const ribIds = group.ribIds.filter((ribId) => intradosLines.some((line) => line.id === ribId));
      if (ribIds.length === 0) continue;
      ribIds.forEach((ribId) => assigned.add(ribId));
      result.push({
        groupId: group.id,
        groupName: resolveGroupName(group.name, ribIds),
        ribIds,
        isGrouped: ribIds.length > 1,
        combinedMeasurements: customGroupMetrics[group.id] ?? fallbackCombined(ribIds),
        source: "custom",
      });
    }

    if (ribGroups) {
      for (const group of ribGroups) {
        if (measurementConfig.disabledAutoGroupIds.includes(group.groupId)) continue;
        if (group.ribIds.some((ribId) => assigned.has(ribId))) continue;

        group.ribIds.forEach((ribId) => assigned.add(ribId));
        result.push({
          ...group,
          groupName: measurementConfig.groupNameById[group.groupId] ?? composeGroupName(group.ribIds) ?? group.groupName,
          source: group.isGrouped ? "auto" : "single",
        });
      }
    }

    for (const line of intradosLines) {
      if (assigned.has(line.id)) continue;
      const measurement = measurementById.get(line.id);
      result.push({
        groupId: line.id,
        groupName: getRibDisplayName(line.id),
        ribIds: [line.id],
        isGrouped: false,
        combinedMeasurements: {
          arc_radius: measurement?.arcRadius ?? 0,
          rib_length: measurement?.ribLength ?? 0,
          apex_point: { x: 0, y: 0, z: 0 },
          arc_center: { x: 0, y: 0, z: 0 },
          arc_center_z: 0,
          fit_error: 0,
        },
        source: "single",
      });
    }

    return result;
  }, [
    composeGroupName,
    customGroupMetrics,
    getRibDisplayName,
    intradosLines,
    measurementById,
    measurementConfig.customGroups,
    measurementConfig.disabledAutoGroupIds,
    measurementConfig.groupNameById,
    resolveGroupName,
    ribGroups,
  ]);

  const displayGroupById = useMemo(() => {
    const byId = new Map<string, DisplayGroup>();
    displayGroups.forEach((group) => {
      byId.set(group.groupId, group);
    });
    return byId;
  }, [displayGroups]);

  const displayGroupIdByRibId = useMemo(() => {
    const byRibId = new Map<string, string>();
    displayGroups.forEach((group) => {
      group.ribIds.forEach((ribId) => {
        byRibId.set(ribId, group.groupId);
      });
    });
    return byRibId;
  }, [displayGroups]);

  const availableRibIdSet = useMemo(() => new Set(intradosLines.map((line) => line.id)), [intradosLines]);

  const pairingDisplayName = useCallback(
    (id: string) => {
      const group = displayGroups.find((candidate) => candidate.groupId === id);
      if (!group) return id;
      if (group.groupName) return group.groupName;
      if (group.ribIds.length === 1) {
        return getRibDisplayName(group.ribIds[0]);
      }
      return composeGroupName(group.ribIds) ?? `Group (${group.ribIds.length} ribs)`;
    },
    [composeGroupName, displayGroups, getRibDisplayName],
  );

  const semicircularGroupIds = useMemo(() => {
    const semicircularRibIds = new Set(measurementConfig.semicircularIds ?? []);
    const groupIds = new Set<string>();
    displayGroups.forEach((group) => {
      if (group.ribIds.length > 0 && group.ribIds.every((ribId) => semicircularRibIds.has(ribId))) {
        groupIds.add(group.groupId);
      }
    });
    return groupIds;
  }, [displayGroups, measurementConfig.semicircularIds]);

  const pairingApexInputs = useMemo(() => {
    return (measurementConfig.ribPairings ?? []).map((pairing) => ({
      pairingId: pairing.id,
      pairingName: pairing.name,
      sides: pairing.sides.map((sideId) => {
        const group = displayGroupById.get(sideId);
        const sideRibIds = group ? group.ribIds : [sideId];
        return {
          sideId,
          sideLabel: pairingDisplayName(sideId),
          ribIds: sideRibIds.filter((ribId) => availableRibIdSet.has(ribId)),
        };
      }),
    }));
  }, [availableRibIdSet, displayGroupById, measurementConfig.ribPairings, pairingDisplayName]);

  const semicircularInputs = useMemo((): SemicircularGroupInput[] => {
    const ids = new Set(measurementConfig.semicircularIds ?? []);
    if (ids.size === 0) return [];

    return displayGroups
      .filter((group) => group.ribIds.length > 0 && group.ribIds.every((ribId) => ids.has(ribId)))
      .map((group) => ({
        groupId: group.groupId,
        groupName: group.groupName ?? group.groupId,
        ribIds: group.ribIds.filter((ribId) => availableRibIdSet.has(ribId)),
      }))
      .filter((group) => group.ribIds.length > 0);
  }, [availableRibIdSet, displayGroups, measurementConfig.semicircularIds]);

  useEffect(() => {
    const loadApexSpan = async () => {
      if (intradosLines.length === 0) {
        setApexSpanResult(null);
        return;
      }

      if (bossStoneMarkers.length === 0 && pairingApexInputs.length === 0 && semicircularInputs.length === 0) {
        setApexSpanResult(null);
        return;
      }

      setIsLoadingApexSpan(true);
      try {
        const response = await calculateApexSpan({
          ribs: intradosLines.map((line) => ({ id: line.id, points: line.points3d })),
          bosses: bossStoneMarkers.map((marker) => ({
            id: marker.id,
            x: marker.x,
            y: marker.y,
            z: marker.z,
            label: marker.label ?? marker.id,
          })),
          maxBossDistance: 0.5,
          impostHeight: impostLineData?.impost_height ?? undefined,
          pairings: pairingApexInputs.length > 0 ? pairingApexInputs : undefined,
          semicircularGroups: semicircularInputs.length > 0 ? semicircularInputs : undefined,
        });

        if (response.success && response.data) {
          setApexSpanResult(response.data);
        } else {
          setApexSpanResult(null);
        }
      } catch (err) {
        console.error("Error calculating apex/span for Step 8 summary:", err);
        setApexSpanResult(null);
      } finally {
        setIsLoadingApexSpan(false);
      }
    };

    void loadApexSpan();
  }, [bossStoneMarkers, impostLineData?.impost_height, intradosLines, pairingApexInputs, semicircularInputs]);

  const findPairingForRibIds = useCallback(
    (ribIds: string[]): RibPairing | undefined => {
      return (measurementConfig.ribPairings ?? []).find((pairing) =>
        pairing.sides.some((sideId) => {
          const group = displayGroupById.get(sideId);
          const sideRibIds = group ? group.ribIds : [sideId];
          return sideRibIds.some((ribId) => ribIds.includes(ribId));
        }),
      );
    },
    [displayGroupById, measurementConfig.ribPairings],
  );

  const resolveGroupImpostDistance = useCallback(
    (group: DisplayGroup): number | null => {
      if (!impostLineData) return null;

      const center = group.combinedMeasurements.arc_center;
      const combinedCenterLooksDerived =
        hasFiniteNumber(group.combinedMeasurements.arc_center_z) &&
        (Math.abs(center.x) > 1e-9 || Math.abs(center.y) > 1e-9 || Math.abs(center.z) > 1e-9);

      if (combinedCenterLooksDerived) {
        return group.combinedMeasurements.arc_center_z - impostLineData.impost_height;
      }

      const ribCenterValues = group.ribIds
        .map((ribId) => impostLineData.ribs[ribId]?.arc_center_z)
        .filter(hasFiniteNumber);

      if (ribCenterValues.length === 0) {
        return null;
      }

      const averageCenterZ = ribCenterValues.reduce((sum, value) => sum + value, 0) / ribCenterValues.length;
      return averageCenterZ - impostLineData.impost_height;
    },
    [impostLineData],
  );

  const ribSummaryRows = useMemo((): RibSummaryRow[] => {
    const impostHeight = impostLineData?.impost_height ?? 0;

    return displayGroups.map((group) => {
      const arcRadius = hasFiniteNumber(group.combinedMeasurements.arc_radius) ? group.combinedMeasurements.arc_radius : null;
      const ribLength = hasFiniteNumber(group.combinedMeasurements.rib_length) ? group.combinedMeasurements.rib_length : null;
      const fitError = hasFiniteNumber(group.combinedMeasurements.fit_error) ? group.combinedMeasurements.fit_error : null;

      const hasArcInputs = arcRadius != null && arcRadius > 0 && ribLength != null && ribLength > 0;
      const straightRib = hasArcInputs && !hasDisplayableRadius(arcRadius, ribLength);
      const groupIsSemicircular = group.ribIds.length > 0 && group.ribIds.every((ribId) => semicircularGroupIds.has(displayGroupIdByRibId.get(ribId) ?? ""));
      const groupPairing = findPairingForRibIds(group.ribIds);

      let spanValue: number | null = null;
      if (hasArcInputs && !straightRib) {
        if (groupIsSemicircular) {
          const semResult = apexSpanResult?.semicircularApex?.find((result) => result.groupId === group.groupId);
          if (semResult?.status === "ok" && hasFiniteNumber(semResult.span)) {
            spanValue = semResult.span;
          }
        } else {
          const groupSpan = group.ribIds.map((ribId) => apexSpanResult?.ribs[ribId]).find((result) => result != null);
          if (groupSpan && hasFiniteNumber(groupSpan.span)) {
            spanValue = groupSpan.span;
          }
        }
      }

      let apexHeightValue: number | null = null;
      if (groupIsSemicircular) {
        const semResult = apexSpanResult?.semicircularApex?.find((result) => result.groupId === group.groupId);
        if (semResult?.status === "ok" && hasFiniteNumber(semResult.apexHeight)) {
          apexHeightValue = semResult.apexHeight - impostHeight;
        }
      } else if (groupPairing) {
        const pairingResult = apexSpanResult?.pairingApex?.find((result) => result.pairingId === groupPairing.id);
        if (pairingResult?.status === "ok" && hasFiniteNumber(pairingResult.apexHeight)) {
          apexHeightValue = pairingResult.apexHeight - impostHeight;
        }
      }

      const impostDistance = resolveGroupImpostDistance(group);
      const displayName = group.groupName ?? group.groupId;

      return {
        id: group.groupId,
        name: displayName,
        source: group.source,
        ribCount: group.ribIds.length,
        arcRadius,
        arcRadiusText: hasArcInputs && !straightRib ? formatMeters(arcRadius, 2) : "N/A",
        length: ribLength,
        lengthText: formatMeters(ribLength ?? 0, 2),
        impostDistance,
        impostDistanceText: impostDistance == null ? "N/A" : formatMeters(impostDistance, 3),
        span: spanValue,
        spanText: spanValue == null ? "N/A" : formatMeters(spanValue, 2),
        apexHeight: apexHeightValue,
        apexHeightText: apexHeightValue == null ? "N/A" : formatMeters(apexHeightValue, 3),
        fitError,
        fitErrorText: fitError == null ? "N/A" : formatMeters(fitError, 4),
      };
    });
  }, [
    apexSpanResult,
    displayGroupIdByRibId,
    displayGroups,
    findPairingForRibIds,
    impostLineData?.impost_height,
    resolveGroupImpostDistance,
    semicircularGroupIds,
  ]);

  const ribToBossMap = useMemo(() => {
    const map = new Map<string, { low: string; high: string }>();
    if (!bossStoneMarkers.length || !intradosLines.length) return map;

    for (const line of intradosLines) {
      if (line.points3d.length < 2) continue;
      const first = line.points3d[0];
      const last = line.points3d[line.points3d.length - 1];
      const firstIsHigh = first[2] >= last[2];
      const highPoint = firstIsHigh ? first : last;
      const lowPoint = firstIsHigh ? last : first;

      let bestHigh = { id: "", dist: Number.POSITIVE_INFINITY };
      let bestLow = { id: "", dist: Number.POSITIVE_INFINITY };

      for (const boss of bossStoneMarkers) {
        const highDist = Math.hypot(highPoint[0] - boss.x, highPoint[1] - boss.y, highPoint[2] - boss.z);
        if (highDist < bestHigh.dist) {
          bestHigh = { id: boss.id, dist: highDist };
        }

        const lowDist = Math.hypot(lowPoint[0] - boss.x, lowPoint[1] - boss.y, lowPoint[2] - boss.z);
        if (lowDist < bestLow.dist) {
          bestLow = { id: boss.id, dist: lowDist };
        }
      }

      if (bestHigh.id && bestLow.id) {
        map.set(line.id, { low: bestLow.id, high: bestHigh.id });
      }
    }

    return map;
  }, [bossStoneMarkers, intradosLines]);

  const bossSummaryRows = useMemo((): BossSummaryRow[] => {
    const impostHeight = impostLineData?.impost_height ?? 0;

    return bossStoneMarkers.map((marker) => {
      const displayName = measurementConfig.bossStoneNameById[marker.id] ?? marker.label;
      const bossApex = apexSpanResult?.bosses.find((boss) => boss.bossId === marker.id);

      const bossPairingResults = (measurementConfig.ribPairings ?? [])
        .filter((pairing) => {
          const pairingInput = pairingApexInputs.find((input) => input.pairingId === pairing.id);
          const pairingRibIds = pairingInput?.sides.flatMap((side) => side.ribIds) ?? [];
          return pairingRibIds.some((ribId) => ribToBossMap.get(ribId)?.high === marker.id);
        })
        .map((pairing) => apexSpanResult?.pairingApex?.find((result) => result.pairingId === pairing.id))
        .filter(
          (result): result is NonNullable<typeof result> =>
            result?.status === "ok" && typeof result.apexHeight === "number",
        );

      const pairingApexHeights = bossPairingResults.map((result) => result.apexHeight as number);
      const medianApexZ = pairingApexHeights.length > 0 ? median(pairingApexHeights) : bossApex?.apex.z;
      const heightFromImpost = medianApexZ != null && Number.isFinite(medianApexZ) ? medianApexZ - impostHeight : null;

      const connectedRibCount = intradosLines.filter((line) => {
        const mapping = ribToBossMap.get(line.id);
        return mapping?.high === marker.id || mapping?.low === marker.id;
      }).length;

      const source: BossSummaryRow["source"] = pairingApexHeights.length > 0 ? "pairings" : bossApex ? "boss-apex" : "n/a";

      return {
        id: marker.id,
        name: displayName,
        groupId: marker.groupId,
        x: marker.x,
        y: marker.y,
        z: marker.z,
        heightFromImpost,
        heightFromImpostText: heightFromImpost == null ? "N/A" : formatMeters(heightFromImpost, 2),
        connectedRibCount,
        apexPairCount: bossApex?.ribPairs.length ?? 0,
        source,
      };
    });
  }, [
    apexSpanResult,
    bossStoneMarkers,
    impostLineData?.impost_height,
    intradosLines,
    measurementConfig.bossStoneNameById,
    measurementConfig.ribPairings,
    pairingApexInputs,
    ribToBossMap,
  ]);

  const ribStats = useMemo(() => {
    const radiusValues = ribSummaryRows.map((row) => row.arcRadius).filter(hasFiniteNumber);
    const fitErrorValues = ribSummaryRows.map((row) => row.fitError).filter(hasFiniteNumber);

    const averageRadius = radiusValues.length > 0
      ? radiusValues.reduce((sum, value) => sum + value, 0) / radiusValues.length
      : null;
    const averageFitError = fitErrorValues.length > 0
      ? fitErrorValues.reduce((sum, value) => sum + value, 0) / fitErrorValues.length
      : null;

    return {
      groupedRows: ribSummaryRows.filter((row) => row.ribCount > 1).length,
      averageRadius,
      averageFitError,
    };
  }, [ribSummaryRows]);

  const bossStats = useMemo(() => {
    const heightValues = bossSummaryRows.map((row) => row.heightFromImpost).filter(hasFiniteNumber);
    const averageHeight = heightValues.length > 0
      ? heightValues.reduce((sum, value) => sum + value, 0) / heightValues.length
      : null;
    return {
      bossesWithHeights: heightValues.length,
      averageHeight,
    };
  }, [bossSummaryRows]);

  const totalSegmentations = currentProject?.segmentations.length || 0;
  const visibleSegmentations = currentProject?.segmentations.filter((segmentation) => segmentation.visible).length || 0;
  const totalProjections = currentProject?.projections.length || 0;
  const totalMeasurements = currentProject?.measurements.length || 0;
  const totalHypotheses = currentProject?.hypotheses.length || 0;
  const totalPointCount = currentProject?.pointCloudStats?.pointCount || 0;
  const totalIntradosLines = currentProject?.intradosLines.length || 0;
  const totalReprojectionSelections = currentProject?.reprojectionSelections.length || 0;

  const chordMethodResult = currentProject?.chordMethodResult;

  const handleRefreshSummary = () => {
    setReloadNonce((value) => value + 1);
  };

  const handleDownloadRibSummary = () => {
    if (ribSummaryRows.length === 0) return;
    setExportingRibs(true);
    try {
      const rows: string[] = [];
      rows.push(["Name", "ArcRadius", "Length", "ImpostDistance", "Span", "ApexHeight", "FitError"].join(","));

      ribSummaryRows.forEach((row) => {
        rows.push(
          [
            toCsvCell(row.name),
            toCsvCell(row.arcRadiusText),
            toCsvCell(row.lengthText),
            toCsvCell(row.impostDistanceText),
            toCsvCell(row.spanText),
            toCsvCell(row.apexHeightText),
            toCsvCell(row.fitErrorText),
          ].join(","),
        );
      });

      downloadCsv(`ribs_export_${Date.now()}.csv`, rows.join("\n"));
    } finally {
      setExportingRibs(false);
    }
  };

  const handleDownloadBossSummary = () => {
    if (bossSummaryRows.length === 0) return;
    setExportingBosses(true);
    try {
      const rows: string[] = [];
      rows.push(["BossStone", "HeightFromImpost"].join(","));
      bossSummaryRows.forEach((row) => {
        rows.push([toCsvCell(row.name), toCsvCell(row.heightFromImpostText)].join(","));
      });
      downloadCsv(`boss_stones_export_${Date.now()}.csv`, rows.join("\n"));
    } finally {
      setExportingBosses(false);
    }
  };

  const handleFinish = () => {
    completeStep(8, {
      viewedAt: new Date().toISOString(),
      summary: {
        projections: totalProjections,
        segmentations: totalSegmentations,
        measurements: totalMeasurements,
        hypotheses: totalHypotheses,
        chordMethod: chordMethodResult?.predictedMethod || null,
      },
    });
    router.push("/");
  };

  if (!currentProject) {
    return (
      <div className="space-y-6">
        <StepHeader
          title="Workflow Results Summary"
          description="No project is loaded. Open a project to view 2D and 3D result summaries."
        />

        <Card>
          <CardContent className="py-10 text-center">
            <Circle className="mx-auto h-12 w-12 text-muted-foreground/60" />
            <p className="mt-3 text-sm text-muted-foreground">No active project data available.</p>
          </CardContent>
        </Card>

        <StepActions>
          <Button onClick={() => router.push("/")} className="gap-2">
            <Home className="h-4 w-4" />
            Return Home
          </Button>
        </StepActions>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <StepHeader
        title="Workflow Results Summary"
        description="Review saved outputs from the 2D and 3D workflow stages"
      />

      <Tabs defaultValue="2d" className="space-y-6">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="2d" className="gap-2">
            <Grid3X3 className="h-4 w-4" />
            2D
          </TabsTrigger>
          <TabsTrigger value="3d" className="gap-2">
            <Box className="h-4 w-4" />
            3D
          </TabsTrigger>
        </TabsList>

        <TabsContent value="2d" />

        <TabsContent value="3d" className="space-y-6">
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <MetricCard
              title="Point Count"
              value={formatNumber(totalPointCount)}
              description="Loaded from Step 1"
              icon={Box}
            />
            <MetricCard
              title="Intrados Lines"
              value={String(totalIntradosLines)}
              description="Tracked in Step 6"
              icon={Circle}
            />
            <MetricCard
              title="Measurements"
              value={String(totalMeasurements)}
              description="Saved in Step 7"
              icon={Table}
            />
            <MetricCard
              title="Hypotheses"
              value={String(totalHypotheses)}
              description="Grouped measurement sets"
              icon={CheckCircle}
            />
          </div>

          <Card>
            <CardHeader className="gap-4 md:flex md:flex-row md:items-start md:justify-between">
              <div className="space-y-1">
                <CardTitle className="font-display">Step 7 Data Summary</CardTitle>
                <CardDescription>
                  Recomputed summary for ribs and boss stones using the same export columns as Step 7B.
                </CardDescription>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <Button
                  variant="outline"
                  onClick={handleRefreshSummary}
                  disabled={isSummaryLoading}
                  className="gap-2"
                >
                  <RefreshCw className={`h-4 w-4 ${isSummaryLoading ? "animate-spin" : ""}`} />
                  Refresh
                </Button>
                <Button
                  variant="outline"
                  onClick={handleDownloadRibSummary}
                  disabled={ribSummaryRows.length === 0 || exportingRibs}
                  className="gap-2"
                >
                  {exportingRibs ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                  Download Ribs CSV
                </Button>
                <Button
                  variant="outline"
                  onClick={handleDownloadBossSummary}
                  disabled={bossSummaryRows.length === 0 || exportingBosses}
                  className="gap-2"
                >
                  {exportingBosses ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                  Download Boss CSV
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <MetricCard
                  title="Rib Rows"
                  value={String(ribSummaryRows.length)}
                  description={`${ribStats.groupedRows} grouped rows`}
                  icon={Table}
                />
                <MetricCard
                  title="Avg Arc Radius"
                  value={ribStats.averageRadius == null ? "n/a" : formatMeters(ribStats.averageRadius, 2)}
                  description={activeTraceSummary}
                  icon={Circle}
                />
                <MetricCard
                  title="Avg Fit Error"
                  value={ribStats.averageFitError == null ? "n/a" : formatMeters(ribStats.averageFitError, 4)}
                  description="Computed from grouped ribs"
                  icon={CheckCircle}
                />
                <MetricCard
                  title="Boss Heights"
                  value={`${bossStats.bossesWithHeights}/${bossSummaryRows.length}`}
                  description={
                    bossStats.averageHeight == null
                      ? "No apex height data"
                      : `avg ${formatMeters(bossStats.averageHeight, 2)}`
                  }
                  icon={Box}
                />
              </div>

              {(isSummaryLoading || isDetectingGroups || isLoadingImpost || isLoadingApexSpan) && (
                <div className="rounded-lg border border-dashed p-3 text-sm text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Refreshing derived summary values...
                  </div>
                </div>
              )}

              {summaryError && (
                <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800">
                  {summaryError}
                </div>
              )}

              <div className="space-y-2">
                <h3 className="text-sm font-semibold">Rib Summary</h3>
                {ribSummaryRows.length > 0 ? (
                  <div className="overflow-x-auto rounded-lg border">
                    <table className="w-full text-sm">
                      <thead className="bg-muted/40 text-left">
                        <tr>
                          <th className="px-3 py-2 font-medium">Name</th>
                          <th className="px-3 py-2 font-medium">Source</th>
                          <th className="px-3 py-2 text-right font-medium">Ribs</th>
                          <th className="px-3 py-2 text-right font-medium">Arc Radius</th>
                          <th className="px-3 py-2 text-right font-medium">Length</th>
                          <th className="px-3 py-2 text-right font-medium">Impost Distance</th>
                          <th className="px-3 py-2 text-right font-medium">Span</th>
                          <th className="px-3 py-2 text-right font-medium">Apex Height</th>
                          <th className="px-3 py-2 text-right font-medium">Fit Error</th>
                        </tr>
                      </thead>
                      <tbody>
                        {ribSummaryRows.map((row, index) => (
                          <tr key={row.id} className={index % 2 === 0 ? "bg-muted/20" : ""}>
                            <td className="px-3 py-2 font-medium">{row.name}</td>
                            <td className="px-3 py-2 text-muted-foreground uppercase tracking-wide">{row.source}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.ribCount}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.arcRadiusText}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.lengthText}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.impostDistanceText}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.spanText}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.apexHeightText}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.fitErrorText}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                ) : (
                  <div className="rounded-lg border border-dashed py-8 text-center text-sm text-muted-foreground">
                    No rib summary data is available.
                  </div>
                )}
              </div>

              <div className="space-y-2">
                <h3 className="text-sm font-semibold">Boss Stone Summary</h3>
                {bossSummaryRows.length > 0 ? (
                  <div className="overflow-x-auto rounded-lg border">
                    <table className="w-full text-sm">
                      <thead className="bg-muted/40 text-left">
                        <tr>
                          <th className="px-3 py-2 font-medium">Boss Stone</th>
                          <th className="px-3 py-2 font-medium">Group</th>
                          <th className="px-3 py-2 text-right font-medium">Height From Impost</th>
                          <th className="px-3 py-2 text-right font-medium">Connected Ribs</th>
                          <th className="px-3 py-2 text-right font-medium">Apex Pairs</th>
                          <th className="px-3 py-2 text-right font-medium">X</th>
                          <th className="px-3 py-2 text-right font-medium">Y</th>
                          <th className="px-3 py-2 text-right font-medium">Z</th>
                          <th className="px-3 py-2 text-right font-medium">Source</th>
                        </tr>
                      </thead>
                      <tbody>
                        {bossSummaryRows.map((row, index) => (
                          <tr key={row.id} className={index % 2 === 0 ? "bg-muted/20" : ""}>
                            <td className="px-3 py-2 font-medium">{row.name}</td>
                            <td className="px-3 py-2 text-muted-foreground">{row.groupId}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.heightFromImpostText}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.connectedRibCount}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{row.apexPairCount}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{formatMetric(row.x, 3)}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{formatMetric(row.y, 3)}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground">{formatMetric(row.z, 3)}</td>
                            <td className="px-3 py-2 text-right text-muted-foreground uppercase tracking-wide">{row.source}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                ) : (
                  <div className="rounded-lg border border-dashed py-8 text-center text-sm text-muted-foreground">
                    No boss stone summary data is available.
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="font-display">Point Cloud and Traces</CardTitle>
              <CardDescription>3D context pulled from Steps 1, 5, and 6</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="rounded-lg border">
                <table className="w-full text-sm">
                  <tbody>
                    <tr>
                      <td className="px-3 py-2 font-medium">Point cloud points</td>
                      <td className="px-3 py-2 text-right text-muted-foreground">{formatNumber(totalPointCount)}</td>
                    </tr>
                    <tr className="bg-muted/30">
                      <td className="px-3 py-2 font-medium">Reprojection selections</td>
                      <td className="px-3 py-2 text-right text-muted-foreground">{totalReprojectionSelections}</td>
                    </tr>
                    <tr>
                      <td className="px-3 py-2 font-medium">Intrados lines</td>
                      <td className="px-3 py-2 text-right text-muted-foreground">{totalIntradosLines}</td>
                    </tr>
                    <tr className="bg-muted/30">
                      <td className="px-3 py-2 font-medium">Summary trace source</td>
                      <td className="px-3 py-2 text-right text-muted-foreground">{activeTraceSource}</td>
                    </tr>
                    <tr className="bg-muted/30">
                      <td className="px-3 py-2 font-medium">Imported 3D traces</td>
                      <td className="px-3 py-2 text-right text-muted-foreground">{currentProject.traces3D.length}</td>
                    </tr>
                    <tr>
                      <td className="px-3 py-2 font-medium">Bounding box available</td>
                      <td className="px-3 py-2 text-right text-muted-foreground">
                        {currentProject.pointCloudStats?.boundingBox ? "yes" : "no"}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <StepActions>
        <Button variant="outline" onClick={() => router.push("/workflow/step-7-measurements")} className="gap-2">
          <ChevronLeft className="h-4 w-4" />
          Back to Measurements
        </Button>
        <Button onClick={handleFinish} className="gap-2">
          <Home className="h-4 w-4" />
          Complete & Return Home
        </Button>
      </StepActions>
    </div>
  );
}
